---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool
  namespace: kube-system
  labels:
    tier: node
    app: multitool
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        tier: node
        app: multitool
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: multitool
        image: woozymasta/network-multitool
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "50m"
            memory: "50Mi"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]

---
apiVersion: v1
kind: Service
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  ports:
  - port: 80
    name: multitool-http
    targetPort: http
  - port: 443
    name: multitool-https
    targetPort: https
  type: ClusterIP
  selector:
    app: multitool
