---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
  labels:
    tier: node
    app: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        tier: node
        app: multitool
    spec:
      containers:
      - name: multitool
        image: woozymasta/network-multitool
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "50m"
            memory: "50Mi"
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: multitool
  labels:
    tier: node
    app: multitool
spec:
  ports:
  - port: 80
    name: multitool-http
    targetPort: http
  - port: 443
    name: multitool-https
    targetPort: https
  type: ClusterIP
  selector:
    app: multitool
